config/routes.rb
Notifier::Application.routes.draw do
  root 'campaigns#index'

  resources :campaigns do
    resources :notifications
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  validates :name, presence: true
  has_many :notifications, dependent: :destroy

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  include IceCube
  serialize :schedule, Hash

  belongs_to :campaign
  validates :title, presence: true
  validates :message, presence: true

  def schedule
    Schedule.from_hash(read_attribute(:schedule))
  end

  def schedule=(value)
    write_attribute(:schedule, value.to_hash)
  end

  def day
    no = schedule.next_occurrence
    return Date::DAYNAMES[no.to_time.wday].downcase unless no.nil?
  end

  def hour
    no = schedule.next_occurrence
    return no.to_time.hour unless no.nil?
  end

  def duration
    no = schedule.next_occurrence
    return no.duration / 3600 unless no.nil?
  end

  def active
    return schedule.occurs_on?(Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :get_campaign, only: [:show, :destroy]

  def index
    @campaigns = Campaign.all
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    if @campaign.save
      redirect_to @campaign
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @campaign.destroy
    redirect_to root_path
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name)
  end

  def get_campaign
    @campaign = Campaign.find_by(id: params[:id])
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :get_campaign, only: [:create, :update, :new, :show, :edit, :destroy]
  before_action :get_notification, only: [:show, :edit, :destroy]

  def index
    @notifications = Notifications.all
  end

  def create
    @notification = @campaign.notifications.build(notification_params)
    @notification.schedule = build_schedule
    if @notification.save
      flash[:success] = 'Notification created successfully'
      redirect_to campaign_notification_path(@campaign, @notification)
    else
      render 'new'
    end
  end

  def update
    @notification = @campaign.notifications.find_by(id: params[:id])
    @notification.schedule = build_schedule
    if @notification.update_attributes(notification_params)
      redirect_to @campaign
    end
  end

  def new
    @notification = @campaign.notifications.build
  end

  def show
  end

  def edit
  end

  def destroy
    @notification.destroy
    flash[:success] = 'Notification deleted'
    redirect_to @campaign
  end

  private

  def get_campaign
    @campaign = Campaign.find_by(id: params[:campaign_id])
  end

  def get_notification
    @notification = @campaign.notifications.find_by(id: params[:id])
  end

  def notification_params
    params.require(:notification).permit(:title,
                                         :message)
  end

  def schedule_params
    params.require(:notification).permit(:day, :hour, :duration)
  end

  def build_schedule
    schedule = IceCube::Schedule.new
    schedule.duration = schedule_params[:duration].to_i * IceCube::ONE_HOUR
    rule = IceCube::Rule.weekly
    rule.day(schedule_params[:day].to_sym)
    rule.hour_of_day(schedule_params[:hour].to_i)
    schedule.add_recurrence_rule(rule)
    schedule
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def weekdays_for_select
    [
        ['Monday', 'monday'],
        ['Tuesday', 'tuesday'],
        ['Wednesday', 'wednesday'],
        ['Thursday', 'thursday'],
        ['Friday', 'friday'],
        ['Saturday', 'saturday'],
        ['Sunday', 'sunday'],
    ]
  end

  def full_title(page_title)
    base_title = "DC Notifier"
    if page_title.empty?
      base_title
    else
      "#{base_title} :: #{page_title}"
    end
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/application/_alert.html.slim
div class="alert alert-#{type}"
  button.close type='button' data-dismiss='alert' aria-hidden='true'
    | &times;
  p #{message.html_safe}

app/views/campaigns/_form.html.slim
= form_for @campaign, html: { role: 'form' } do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-primary'
  = link_to 'Cancel', root_path, class: 'btn btn-default'

app/views/campaigns/index.html.slim
h1 Campaigns
- unless @campaigns.empty?
  table.table.table-striped.campaign-table
    thead
      tr
        th
        th
        th
    tbody
      - for c in @campaigns do
        tr
          td: h4 = c.name
          td = link_to 'View', campaign_path(c), class: 'btn btn-default'
          td = link_to 'Delete', campaign_path(c), method: :delete, class: 'btn btn-default', confirm: 'Are you sure?'
= link_to 'Create', new_campaign_path, class: 'btn btn-default'

app/views/campaigns/new.html.slim
h1 Create Campaign

= render 'form'

app/views/campaigns/show.html.slim
h1 = @campaign.name
hr

- unless @campaign.notifications.empty?
  table.table.table-striped.campaign-table
    thead
      tr
        th Notifications
        th
        th
        th
    tbody
      - for n in @campaign.notifications
        tr
          td: h4 = n.title
          td = link_to 'View', campaign_notification_path(@campaign, n), class: 'btn btn-default'
          td = link_to 'Edit', edit_campaign_notification_path(@campaign, n), class: 'btn btn-default'
          td = link_to 'Delete', campaign_notification_path(@campaign, n), method: :delete, class: 'btn btn-default', confirm: 'Are you sure?'
- else
  p This campaign has no notifications

= link_to 'Add Notification', new_campaign_notification_path(@campaign), class: 'btn btn-default'
hr
p To add this campaign to your website, paste the following directly before your site's &lt;/body&gt; tag
  on any pages the notifications should get displayed.
pre &lt;script type=&quot;text/javascript&quot;&gt;
      var _bconf = _bconf || {};
      _bconf['_key'] = '#{@campaign.id}';
    &lt;/script&gt;
    &lt;script src='#{request.base_url}/notifier.js'&gt;&lt;/script&gt;

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default role='navigation'
  .navbar-header
    button.navbar-toggle type='button' data-toggle='collapse' data-target='#main-nav'
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href='/' DC Notifier

  .collapse.navbar-collapse id='main-nav'
    ul.nav.navbar-nav
      - if current_page?(root_path)
        li.active: a href='/' Campaigns
      - else
        li: a href='/' Campaigns

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    == stylesheet_link_tag 'application', media: 'all'
    == csrf_meta_tags

  body
    .container
      .row
        .col-md-6.col-md-offset-3
          = render 'layouts/navigation'

          - flash.each do |key, value|
            = render 'application/alert', type: key, message: value

          == yield
    == javascript_include_tag 'application'

app/views/notifications/_form.html.slim
= form_for [@campaign, @notification], html: { role: 'form' } do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :message
    = f.text_area :message, class: 'form-control', rows: 3
  .form-group
    = f.label :day
    = f.select :day, weekdays_for_select, {}, { class: 'form-control' }
  .form-group
    = f.label :hour
    = f.text_field :hour, class: 'form-control'
  .form-group
    = f.label :duration
    = f.text_field :duration, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-primary'
  = link_to 'Cancel', campaign_path(@campaign), class: 'btn btn-default'

app/views/notifications/edit.html.slim
h1 Edit

= render 'form'

app/views/notifications/new.html.slim
= provide(:title, "New Notification")
h1 New Notification

= render 'form'

app/views/notifications/show.html.slim
h1 Notification

p Title: #{@notification.title}
p Message: #{@notification.message}
p Key: #{@notification.id}

hr

p
  = link_to 'Edit', edit_campaign_notification_path(@campaign, @notification), class: 'btn btn-default'

javascript:
  var _bconf = _bconf || {};
  _bconf['_key'] = '#{@campaign.id}';
  _bconf['_note'] = #{@notification.id};
  _bconf['_baseUrl'] = '#{request.base_url}';

script src="#{request.base_url}/notifier.js"